### PR TITLE
Fix syntax highlighting --option-with-hyphen

### LINKED ISSUE #99: CLI syntax highlighting --options-with-hyphen
e.g. https://cml.dev/doc/cml-with-dvc?tab=AWS#runner-access-permissions highlights `--cloud` but not `--cloud-type`:

image

### PR DESCRIPTION
**Pull request by yathomasi**
Screenshot 2022-11-16 at 23 11 01

Fixes #99

### CODE REVIEW

File: packages/gatsby-theme-iterative/config/prismjs/dvc.js [hunk 1]
```diff
@@ -73,7 +73,12 @@ Prism.languages.cli = {
         greedy: true,
         lookbehind: true
       },
-      ...bash
+      ...bash,
+      parameter: {
+        pattern: /(^|\s)-{1,2}(?:\w+:[+-]?)?\w+(?:[\.-]\w+)*(?=[=\s]|$)/,
+        alias: 'variable',
+        lookbehind: true
+      }
```
Comment (rogermparent) [inline packages/gatsby-theme-iterative/config/prismjs/dvc.js:81]: Looking alright to me, though `lookbehind` regex generally makes me react in a way where I think there's a more elegant solution possible. Not a blocker if it works, though.

**Review by rogermparent — APPROVED** [review]

File: packages/gatsby-theme-iterative/config/prismjs/dvc.js (hunk 1 above)
Comment (yathomasi) [reply packages/gatsby-theme-iterative/config/prismjs/dvc.js:81]: I simply took it from https://github.com/PrismJS/prism/blob/master/components/prism-bash.js and added `-` support. I hesitated to do a PR on prism itself because of https://github.com/PrismJS/prism#contribute-to-prism
